Spring:
  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    show-sql: true
    data-base-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

